nu = str(input("Fale um numero"))
div = " ".join(nu).split()
print("A Unidade é {} ".format(div[3]))
print("A dezena é {} ".format(div[2]))
print("A centena é {} ".format(div[1]))
print("O milhar é {} ".format(div[0]))
